version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3000:3000" 
    depends_on:
      - backend
    networks:
      - devops-network
    environment:
      REACT_APP_API_BASE_URL: http://backend:5000

  backend:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "8000:8000" 
    depends_on:
      - mongo
    networks:
      - devops-network
    environment:
      MONGO: mongodb://mongo:27017/lbms-db

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017" 
    networks:
      - devops-network
    volumes:
      - mongo-data:/data/db

networks:
  devops-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local